import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {compileExternalControlOperationV1,finalizeExternalControlReadbackV1} from '../external-control/bridge-v1.mjs';
import {createLocalArtifactCacheV1,evaluateRemoteArtifactReceiptV1} from '../artifacts/local-cache/index.mjs';
import {classifyOrphanV1,reconcileOutcomeUnknownV1} from '../watchdog/orphan-reaper/index.mjs';
import {decideTeardownWatchdogV1} from '../watchdog/teardown-watchdog/index.mjs';
test('P9 external bridge is provider-neutral API-first and no-ops identical state',()=>{const op=compileExternalControlOperationV1({operation:'CONFIG_SET',effectClass:'PROVIDER_MUTATION',providerAdapterId:'fake'});assert.equal(op.apiFirst,true);assert.equal(op.browserFirst,false);assert.equal(op.thirdPartyPaidNormalPath,false);assert.equal(finalizeExternalControlReadbackV1({operation:op,currentState:{x:1},desiredState:{x:1}}).noOpMutationRequired,false);});
test('P10 artifact cache verifies content and never self-accepts',async()=>{const root=await mkdtemp(join(tmpdir(),'ep52-art-'));try{const c=createLocalArtifactCacheV1({root});const ref=await c.put({name:'x.txt',bytes:'hello',retentionClass:'EVIDENCE_RETAINED'});assert.equal((await c.get(ref)).toString(),'hello');assert.equal(ref.runtimeAccepted,false);const rr=evaluateRemoteArtifactReceiptV1({expectedDigest:ref.digest,observedDigest:ref.digest});assert.equal(rr.digestVerified,true);assert.equal(rr.runtimeAccepted,false);assert.equal(await c.remove(ref),true);}finally{await rm(root,{recursive:true,force:true});}});
test('P11 reaper never deletes ambiguous foreign resource and outcome unknown forbids second mutation',()=>{assert.equal(classifyOrphanV1({ownershipProof:{resourceId:'a',valid:true},lease:{resourceId:'a',state:'EXPIRED'},liveResource:{resourceId:'b'}}).autoDelete,false);assert.equal(classifyOrphanV1({ownershipProof:{resourceId:'a',valid:true},lease:{resourceId:'a',state:'EXPIRED'},liveResource:{resourceId:'a'}}).autoDelete,true);assert.equal(reconcileOutcomeUnknownV1({originalOperationId:'op1'}).secondMutationAllowed,false);});
test('P11 teardown watchdog requires ownership proof and full readback chain',()=>{assert.equal(decideTeardownWatchdogV1({workerLost:true,ownershipProofValid:false}).cleanupEligible,false);const d=decideTeardownWatchdogV1({workerLost:true,ownershipProofValid:true});assert.equal(d.action,'SAFE_DESTROY');assert.equal(d.deleteReadbackRequired,true);assert.equal(d.residueScanRequired,true);});
