import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {buildBootstrapBundleV1} from '../bootstrap/bundle/index.mjs';
import {compileWorkerReadyAttestationV1,evaluateWorkerReadyAttestationV1} from '../worker/readiness/index.mjs';
import {buildExecutionPackageV1,compilePreOperationAttestationV1} from '../preoperation/execution-package-v1.mjs';
import {createSecretBrokerV1} from '../secrets/broker-v1.mjs';
const h=s=>createHash('sha256').update(s).digest('hex');

test('P4 immutable bootstrap bundle and readiness are separate from resource creation',()=>{const b=buildBootstrapBundleV1({workerAgentSha256:h('agent'),runnerPackageSha256:h('runner'),entrypointSha256:h('entry'),dependencySetSha256:h('deps'),contractSetSha256:h('contracts')});assert.match(b.BOOTSTRAP_BUNDLE_SHA256,/^[0-9a-f]{64}$/);assert.throws(()=>buildBootstrapBundleV1({mutableTag:'latest'}),/MUTABLE_LATEST_BOOTSTRAP_DENIED/);const a=compileWorkerReadyAttestationV1({workerId:'w1',bootstrapBundleSha256:b.BOOTSTRAP_BUNDLE_SHA256,agentDigest:h('agent'),capabilities:{NODE_VERSION:'v22'},observedAtMs:1000,ttlMs:100});assert.equal(a.resourceCreated,true);assert.equal(a.workerReady,true);assert.equal(evaluateWorkerReadyAttestationV1(a,{nowMs:1050}).ready,true);assert.equal(evaluateWorkerReadyAttestationV1(a,{nowMs:1101}).code,'READINESS_STALE');});

test('P5 execution package is immutable-addressed and pre-operation fails closed',()=>{const pkg=buildExecutionPackageV1({jobContract:{id:'j'},sourceAuthority:{tree:h('tree')},preOperationAttestation:{status:'PENDING'},inputManifest:{},runtimeBootstrap:{},executionEntrypoint:{command:'node'},projectExecutionDeclaration:{executionClass:'HEAVY'},evidenceSchema:{version:'1'},artifactDestination:{mode:'CONTENT_ADDRESSED'},teardownInstructions:{mode:'ALWAYS'}});assert.match(pkg.EXECUTION_PACKAGE_SHA256,/^[0-9a-f]{64}$/);const fail=compilePreOperationAttestationV1({sourceIdentityVerified:true});assert.equal(fail.status,'FAIL');const pass=compilePreOperationAttestationV1({sourceIdentityVerified:true,inputsVerified:true,runtimeFingerprintVerified:true,providerTargetVerified:true,credentialScopeVerified:true,costAdmissionPass:true,executionPackageVerified:true});assert.equal(pass.status,'PASS');});

test('P5 Secret Broker exposes opaque ref and clears secret on revoke',()=>{const b=createSecretBrokerV1();const issued=b.issue({secret:'ephemeral-value',scope:'provider:test',expiresAtMs:2000});assert.match(issued.credentialRef,/^secret:\/\//);assert.equal(issued.rawSecretPersisted,false);assert.equal(b.resolve(issued.credentialRef,{nowMs:1000}),'ephemeral-value');b.revoke(issued.credentialRef);assert.equal(b.inspect(issued.credentialRef).rawSecretPersisted,false);assert.throws(()=>b.resolve(issued.credentialRef,{nowMs:1000}),/CREDENTIAL_REF_INVALID/);});
