import test from "node:test";import assert from "node:assert/strict";
import {compileAuthoritativeJobSnapshotV1} from "../snapshot/job-snapshot-v1.mjs";
import {compileExternalExecutorCapabilityAttestationV1,evaluateExternalExecutorAdmissionV1} from "../v006/executor-trust-v1.mjs";
import {compileExternalExecutionHandoffEnvelopeV1,evaluateHandoffFreshnessV1,compileHandoffReceiptV1,verifyHandoffReceiptChainV1} from "../v006/handoff-envelope-v1.mjs";
import {compileSafeExternalBatchV1,evaluatePreActuationFreshnessV1,evaluateExternalReplayV1,evaluateActuatorClaimV1,evaluateTargetConcurrencyV1} from "../v006/safe-batch-v1.mjs";
import {reconcileExternalPostconditionsV1,compileDurableExternalResumeStateV1,evaluateResumeSignalV1} from "../v006/reconciliation-resume-v1.mjs";
const D="a".repeat(64);
function snapshot(){return compileAuthoritativeJobSnapshotV1({runtimeState:{executionId:"e1",attemptId:"a1",fenceToken:7,authorityState:"ACTIVE",acceptanceState:"PENDING",cancelState:"NONE"},sidecarObservation:{providerClass:"DIGITALOCEAN"}})}
function handoff(){return compileExternalExecutionHandoffEnvelopeV1({authoritativeJobSnapshot:snapshot(),attemptId:"a1",fenceToken:7,leaseGeneration:3,masterPlanRunId:"run1",phaseId:"V006-P3",projectIdentity:"atelier-execution-plane",planDigest:D,sourceManifestDigest:D,payloadDigest:D,instructionDigest:D,runtimeContractSetDigest:D,targetSystem:"DigitalOcean",targetIdentity:"account:acct",executorClass:"PROVIDER_NATIVE_EXECUTOR",requiredCapabilities:["RESOURCE_CREATE","READBACK"],effectClass:"PROVIDER_MUTATION",replayClass:"SINGLE_USE_WRITE",authorityEnvelopeRef:"authority://1",expectedPostconditions:[{id:"resource-active"}],readbackPlan:["provider-inventory"],executorProtocolVersion:"1",rendererProtocolVersion:"1",receiptSchemaVersion:"1",createdAtMs:100,expiresAtMs:1000,resumeAnchorId:"resume1"})}
test("C1 executor admission is capability/TTL/data-policy gated and cannot accept",()=>{const a=compileExternalExecutorCapabilityAttestationV1({executorId:"do",executorClass:"PROVIDER_NATIVE_EXECUTOR",capabilities:["RESOURCE_CREATE","READBACK"],protocolVersion:"1",rendererVersion:"1",receiptSchemaVersion:"1",observedAtMs:10,capabilityTtlMs:100});assert.equal(evaluateExternalExecutorAdmissionV1({attestation:a,requiredCapabilities:["READBACK"],nowMs:50}).allowed,true);assert.equal(a.trustToAccept,false);assert.equal(evaluateExternalExecutorAdmissionV1({attestation:a,requiredCapabilities:["SSH"],nowMs:50}).allowed,false)});
test("C2 handoff is a snapshot projection and fails stale source",()=>{const h=handoff();assert.equal(h.runtimeAcceptanceAuthorityPreserved,true);assert.equal(h.handoffCanAdvanceRuntimeFence,false);const ok=evaluateHandoffFreshnessV1({handoff:h,currentProjectIdentity:h.projectIdentity,currentPlanDigest:h.planDigest,currentSourceManifestDigest:h.sourceManifestDigest,currentAttemptId:h.attemptId,currentLeaseGeneration:h.leaseGeneration,currentFenceToken:h.fenceToken,currentTargetIdentity:h.targetIdentity,nowMs:200});assert.equal(ok.allowed,true);assert.equal(evaluateHandoffFreshnessV1({handoff:h,currentProjectIdentity:h.projectIdentity,currentPlanDigest:h.planDigest,currentSourceManifestDigest:"b".repeat(64),currentAttemptId:h.attemptId,currentLeaseGeneration:h.leaseGeneration,currentFenceToken:h.fenceToken,currentTargetIdentity:h.targetIdentity,nowMs:200}).code,"HANDOFF_STALE")});
test("C2 receipt chain detects digest break",()=>{const h=handoff();const r1=compileHandoffReceiptV1({receiptType:"HANDOFF_CREATED_RECEIPT",handoffDigest:h.handoffDigest,payload:{state:"COMPILED"},createdAtMs:101});const r2=compileHandoffReceiptV1({receiptType:"HANDOFF_DELIVERED_RECEIPT",handoffDigest:h.handoffDigest,previousReceiptDigest:r1.receiptDigest,payload:{state:"DELIVERED"},createdAtMs:102});assert.equal(verifyHandoffReceiptChainV1([r1,r2]).status,"PASS");assert.equal(verifyHandoffReceiptChainV1([r1,{...r2,previousReceiptDigest:"b".repeat(64)}]).status,"FAIL")});
test("C3 safe batch splits at single-use/destructive boundaries",()=>{const p=compileSafeExternalBatchV1({steps:[{id:"r",replayClass:"READ_ONLY",targetIdentity:"t"},{id:"w",replayClass:"SINGLE_USE_WRITE",targetIdentity:"t"},{id:"d",replayClass:"DESTRUCTIVE_WRITE",targetIdentity:"t"}]});assert.equal(p.batches.length,2);assert.equal(evaluateExternalReplayV1({replayClass:"SINGLE_USE_WRITE",outcome:"UNKNOWN"}).retryAllowed,false);assert.equal(evaluatePreActuationFreshnessV1({targetReadbackFresh:true,authorityFenceFresh:true,sourcePlanBindingFresh:true,expectedPreconditionsPass:true}).allowed,true);assert.equal(evaluateActuatorClaimV1({handoffId:"h",existingActiveExecutorId:"x",candidateExecutorId:"y",replayClass:"SINGLE_USE_WRITE"}).allowed,false);assert.equal(evaluateTargetConcurrencyV1({left:{targetIdentity:"a",replayClass:"IDEMPOTENT_WRITE"},right:{targetIdentity:"b",replayClass:"IDEMPOTENT_WRITE"}}).parallel,true)});
test("C4 partial completion resumes missing only and requires authoritative readback",()=>{const h=handoff();const r=reconcileExternalPostconditionsV1({handoffId:h.handoffId,expectedPostconditions:[{id:"a"},{id:"b"}],authoritativeReadback:{a:true,b:false}});assert.deepEqual(r.completedPostconditions,["a"]);assert.deepEqual(r.pendingPostconditions,["b"]);const s=compileDurableExternalResumeStateV1({handoff:h,reconciliation:r,lastAuthoritativeReadbackRef:"artifact://readback",nextLegalAction:"EXECUTE_B"});assert.equal(evaluateResumeSignalV1({resumeState:s,authoritativeReadbackPerformed:false,nowMs:200,currentFenceToken:7}).allowed,false);assert.equal(evaluateResumeSignalV1({resumeState:s,authoritativeReadbackPerformed:true,nowMs:200,currentFenceToken:7}).allowed,true)});
