import test from "node:test";import assert from "node:assert/strict";
import {compileV006LiveReferencePlanV1,evaluateAutomatedMachineReferenceV1,evaluateDurableAuthorityReferenceV1,evaluateHumanActuatedReferenceV1,evaluateWorkstationBatchReferenceV1,evaluateExternalContinuityConformanceV1} from "../v006/live-reference-v1.mjs";
import {evaluateV006OperationalEconomySafetyV1} from "../v006/operational-economy-v1.mjs";
import {compileV006HorizonBoundaryV1} from "../v006/horizon-boundary-v1.mjs";
import {evaluateV006FinalReadinessV1,V006_CORE_CONTRACT_IDS,V006_INTEGRATION_LOCK_IDS,V006_REFERENCE_IDS} from "../v006/final-readiness-v1.mjs";
test("P14-P18 live-reference plans remain Runtime-accepted and fail closed until evidence exists",()=>{const p=compileV006LiveReferencePlanV1({referenceClass:"R1_AUTOMATED_MACHINE_EXTERNAL_EXECUTOR"});assert.equal(p.acceptanceAuthority,"RUNTIME");assert.equal(p.executorSelfAcceptance,false);assert.equal(evaluateAutomatedMachineReferenceV1({}).status,"PENDING");assert.equal(evaluateDurableAuthorityReferenceV1({}).status,"PENDING");assert.equal(evaluateHumanActuatedReferenceV1({}).status,"PENDING");assert.equal(evaluateWorkstationBatchReferenceV1({}).status,"PENDING");assert.equal(evaluateExternalContinuityConformanceV1({}).status,"PENDING")});
test("P19 operational economy requires zero human/auth/retry leakage and zero residue",()=>{const r=evaluateV006OperationalEconomySafetyV1({REPEATED_MICRO_APPROVAL_COUNT:0,REPEATED_MANUAL_TOKEN_MINT_COUNT:0,UNNECESSARY_HUMAN_ROUNDTRIP:0,RAW_CREDENTIAL_TRANSFER_THROUGH_CHAT:0,STALE_HANDOFF_EXECUTION:0,BLIND_EXTERNAL_RETRY:0,DUPLICATE_SINGLE_USE_MUTATION:0,PAID_RESOURCE_CREATED_BEFORE_AUTH_READY:0,AUTHORITATIVE_READBACK_AFTER_EXTERNAL_EXECUTION:100,ACTIVE_PAID_COMPUTE:0,ORPHANED_BILLABLE_RESOURCE:0,BILLABLE_RESIDUE:0,EPHEMERAL_CREDENTIAL_RESIDUE:"NOT_MEASURABLE",EXPIRED_HANDOFF_PAYLOAD_GC:"PASS"});assert.equal(r.status,"PASS");assert.equal(evaluateV006OperationalEconomySafetyV1({...r.metrics,AUTHORITATIVE_READBACK_AFTER_EXTERNAL_EXECUTION:0,ACTIVE_PAID_COMPUTE:0,ORPHANED_BILLABLE_RESOURCE:0,BILLABLE_RESIDUE:0,EPHEMERAL_CREDENTIAL_RESIDUE:0,EXPIRED_HANDOFF_PAYLOAD_GC:"PASS"}).status,"PENDING")});
test("P20 preserves H1 seals and keeps H2 locked before additive integration seal",()=>{const h=compileV006HorizonBoundaryV1({historicalRuntimePiloteSealsPreserved:true,runtimeSourceMutationCount:0,piloteSourceMutationCount:0,horizon1CompatibilityProjectionStatus:"PASS",horizon1IntegrationSealStatus:"PENDING"});assert.equal(h.HORIZON1_V006_COMPATIBILITY_PROJECTION,"PASS");assert.equal(h.HORIZON2_V006_NATIVE_OWNERSHIP_BOUNDARY,"PASS_SOURCE_DEFINED");assert.equal(h.HORIZON2_START_ALLOWED,false)});
test("P21 final readiness requires C1-C8 I1-I8 R1-R6 predecessor controls and residue zero",()=>{const core=Object.fromEntries(V006_CORE_CONTRACT_IDS.map(x=>[x,"PASS"]));const locks=Object.fromEntries(V006_INTEGRATION_LOCK_IDS.map(x=>[x,"PASS"]));const refs=Object.fromEntries(V006_REFERENCE_IDS.map(x=>[x,"PASS"]));const r=evaluateV006FinalReadinessV1({coreContracts:core,integrationLocks:locks,references:refs,predecessorControlsPass:true,ACTIVE_PAID_COMPUTE:0,ORPHANED_BILLABLE_RESOURCE:0,BILLABLE_RESIDUE:0});assert.equal(r.status,"PASS");assert.equal(r.sealEligible,true);refs.R2="PENDING";assert.equal(evaluateV006FinalReadinessV1({coreContracts:core,integrationLocks:locks,references:refs,predecessorControlsPass:true,ACTIVE_PAID_COMPUTE:0,ORPHANED_BILLABLE_RESOURCE:0,BILLABLE_RESIDUE:0}).sealEligible,false)});
