import test from "node:test";import assert from "node:assert/strict";
import {estimateDigitalOceanDropletCostMilliUsdV1,selectMinimumDropletForLiveQualificationV1} from "../providers/digitalocean/cost-aware-selector-v1.mjs";
import {createDigitalOceanOfficialApiSurfaceDriverV1} from "../providers/digitalocean/official-api-surface-driver-v1.mjs";
import {DIGITALOCEAN_MINIMUM_LIVE_SCOPES} from "../providers/digitalocean/api-execution-v1.mjs";

test("cost projection respects billing floor and TTL",()=>{assert.equal(estimateDigitalOceanDropletCostMilliUsdV1({priceHourly:0.006,ttlSeconds:30}),10);assert.equal(estimateDigitalOceanDropletCostMilliUsdV1({priceHourly:0.036,ttlSeconds:1800}),18)});
test("selector chooses minimum eligible size within cost cap",()=>{const s=selectMinimumDropletForLiveQualificationV1({requirements:{minCpu:2,minMemoryMiB:4096,minDiskGiB:20},sizes:[{slug:"small",available:true,vcpus:1,memory:1024,disk:25,price_hourly:0.006,regions:["sgp1"]},{slug:"heavy-a",available:true,vcpus:2,memory:4096,disk:20,price_hourly:0.036,regions:["sgp1"]},{slug:"heavy-b",available:true,vcpus:4,memory:8192,disk:40,price_hourly:0.071,regions:["sgp1"]}],region:"sgp1",ttlSeconds:1800,costCapMilliUsd:100});assert.equal(s.slug,"heavy-a");assert.equal(s.projectedCostMilliUsd,18)});
test("selector refuses over-cap sizes",()=>{assert.throws(()=>selectMinimumDropletForLiveQualificationV1({requirements:{minCpu:2,minMemoryMiB:4096,minDiskGiB:20},sizes:[{slug:"x",available:true,vcpus:2,memory:4096,disk:20,price_hourly:0.25,regions:["sgp1"]}],region:"sgp1",ttlSeconds:1800,costCapMilliUsd:100}),/NO_DIGITALOCEAN_SIZE_WITHIN_REQUIREMENTS_AND_COST_CAP/)});

function fakeApi(){const requests=[];let droplet=null;let deleted=false;return {requests,async request({method,path,query,body}){requests.push({method,path,query,body});if(method==="GET"&&path==="/v2/account")return {status:200,body:{account:{uuid:"acct-1",email:"u@example.com",droplet_limit:10,status:"active"}}};if(method==="GET"&&path==="/v2/sizes")return {status:200,body:{sizes:[{slug:"s-2vcpu-4gb",available:true,vcpus:2,memory:4096,disk:80,price_hourly:0.036,regions:["sgp1"]}]}};if(method==="GET"&&path==="/v2/regions")return {status:200,body:{regions:[{slug:"sgp1",available:true}]}};if(method==="GET"&&path==="/v2/images")return {status:200,body:{images:[{id:24,slug:"ubuntu-24-04-x64",distribution:"Ubuntu",name:"24.04 x64",public:true,status:"available"}]}};if(method==="GET"&&path==="/v2/droplets")return {status:200,body:{droplets:droplet&&!deleted?[droplet]:[]}};if(method==="POST"&&path==="/v2/droplets"){droplet={id:101,name:body.name,status:"active",region:{slug:body.region},size:{slug:body.size},tags:body.tags,networks:{v4:[{ip_address:"203.0.113.10"}]}};return {status:202,body:{droplet}}}if(method==="GET"&&path==="/v2/droplets/101")return deleted?{status:404,body:{}}:{status:200,body:{droplet}};if(method==="GET"&&path==="/v2/droplets/101/destroy_with_associated_resources")return {status:200,body:{snapshots:[],volumes:[],volume_snapshots:[],reserved_ips:[]}};if(method==="DELETE"&&path==="/v2/droplets/101"){deleted=true;return {status:204,body:null}}throw new Error(`UNEXPECTED:${method}:${path}`)},async getAuthMetadata(){return {grantedScopes:DIGITALOCEAN_MINIMUM_LIVE_SCOPES}}}};

test("official API driver performs discovery create readback cleanup and zero residue",async()=>{const f=fakeApi();const d=createDigitalOceanOfficialApiSurfaceDriverV1({request:f.request,getAuthMetadata:f.getAuthMetadata});const plan={executionId:"ep52-do-test"};const context={leaseId:"lease1",requirements:{minCpu:2,minMemoryMiB:4096,minDiskGiB:20},regionPreference:"sgp1",imageSlug:"ubuntu-24-04-x64",ttlSeconds:1800,costCapMilliUsd:100,bootstrapBundleSha256:"a".repeat(64)};const discovery=await d.discover({plan,context});assert.equal(discovery.size.slug,"s-2vcpu-4gb");assert.equal(discovery.size.projectedCostMilliUsd,18);const current=await d.readCurrent({plan,context});const diff=await d.diffDesired({plan,context,current});const mutation=await d.mutateMinimalDelta({diff});assert.equal(mutation.newPaidResourceCreated,true);const readback=await d.authoritativeReadback({plan,context});assert.equal(readback.status,"active");const cleanup=await d.cleanup({plan,context});assert.equal(cleanup.childBillableResourceCount,0);const absent=await d.deleteReadback({plan,context});assert.equal(absent.resourceAbsent,true);const residue=await d.residueScan({plan,context});assert.deepEqual([residue.ACTIVE_PAID_COMPUTE,residue.ORPHANED_BILLABLE_RESOURCE,residue.BILLABLE_RESIDUE],[0,0,0])});
