import test from "node:test";import assert from "node:assert/strict";
import {compileDeferredProviderAttachTicketV1,bindDeferredProviderSurfaceV1} from "../providers/deferred-reattach-v1.mjs";
import {compilePostSealCompatibilityPlanV1,compilePostSealIntegrationLivePlanV1} from "../integration/post-seal-plan-v1.mjs";

const base={branch:"ep52-h1-recovery",sourceHead:"a".repeat(40),sourceTree:"b".repeat(40)};
test("VMware ticket is hot-attachable later without manual SSH, approval reset, or source reset",()=>{const t=compileDeferredProviderAttachTicketV1({...base,provider:"VMWARE"});assert.equal(t.state,"DEFERRED_PROVIDER_LIVE_WORK");assert.equal(t.existingInfrastructureOnly,true);assert.equal(t.newPaidResourceAllowed,false);assert.equal(t.manualSshNormalPath,false);assert.equal(t.termuxNormalPath,false);assert.equal(t.approvalResetOnReattach,false);assert.deepEqual(t.requiredLiveMatrixEdges,["VMWARE::DIRECT_WORKER","VMWARE::GITHUB_SELF_HOSTED_JIT"])});
test("VMware surface receipt becomes HOT_REATTACH_READY only after identity, inventory, auth and capability readback",()=>{const t=compileDeferredProviderAttachTicketV1({...base,provider:"VMWARE"});const r=bindDeferredProviderSurfaceV1({ticket:t,surfaceReceipt:{provider:"VMWARE",surfaceClass:"TRUSTED_EXECUTOR",connectionState:"CONNECTED",authState:"REUSED",targetIdentityReadback:"PASS",inventoryReadback:"PASS",existingAuthReused:true,rawSecretMaterialObserved:false,capabilities:t.requiredCapabilities,executionSurfaceId:"vmware-evening",providerTarget:"vcenter-existing"}});assert.equal(r.decision,"HOT_REATTACH_READY");assert.equal(r.approvalReset,false);assert.equal(r.authReset,false);assert.equal(r.duplicateExecutionAllowed,false)});
test("VMware incomplete surface remains deferred without invalidating source work",()=>{const t=compileDeferredProviderAttachTicketV1({...base,provider:"VMWARE"});const r=bindDeferredProviderSurfaceV1({ticket:t,surfaceReceipt:{provider:"VMWARE",surfaceClass:"TRUSTED_EXECUTOR",connectionState:"DISCONNECTED",authState:"UNKNOWN",targetIdentityReadback:"PENDING",inventoryReadback:"PENDING",capabilities:[]}});assert.equal(r.decision,"REATTACH_NOT_READY");assert.equal(r.nextAction,"REFRESH_SURFACE_WITHOUT_SOURCE_RESET")});
test("DigitalOcean ticket preserves minimum-cost billing firewall for later OAuth reattach",()=>{const t=compileDeferredProviderAttachTicketV1({...base,provider:"DIGITALOCEAN"});assert.equal(t.maxConcurrentPaidResources,1);assert.equal(t.maxPaidComputeMilliUsdPerResource,100);assert.equal(t.maxPaidComputeMilliUsdTotal,500);assert.equal(t.maxTtlSeconds,1800);assert.equal(t.additionalBillableResourcesAllowed,false);assert.equal(t.rawSecretMaterialAllowed,false)});
test("post-seal compatibility and integration-live plans are source-ready but fail closed before Execution Plane handoff",()=>{const p=compilePostSealCompatibilityPlanV1({runtimeDevelopmentSealDigest:"1".repeat(64),piloteDevelopmentSealDigest:"2".repeat(64),historicalFinalSealDigest:"3".repeat(64)});assert.equal(p.state,"WAITING_EXECUTION_PLANE_SEAL_HANDOFF");assert.equal(p.runtimeSourceMutationPlanned,0);assert.equal(p.piloteSourceMutationPlanned,0);const l=compilePostSealIntegrationLivePlanV1({compatibilityRebindStatus:"PENDING"});assert.equal(l.state,"WAITING_COMPATIBILITY_REBIND_PASS");assert.equal(l.repeatHistoricalRev52LiveSuite,false)});
