import test from "node:test";import assert from "node:assert/strict";
import {compileProviderLiveTransactionV1,evaluateProviderLiveTransactionV1,reconcileUnknownProviderOutcomeV1,PROVIDER_LIVE_TRANSACTION_STAGES} from "../live/provider-live-transaction-v1.mjs";
import {createDigitalOceanFakeAdapterV1,compileDigitalOceanProvisionSpecV1} from "../providers/digitalocean/index.mjs";
import {createVmwareFakeAdapterV1,compileVmwareProvisionSpecV1} from "../providers/vmware/index.mjs";

const base={sourceHead:"a".repeat(40),sourceTree:"b".repeat(40),attachTicketDigest:"c".repeat(64)};
const stageReceipts=(plan)=>PROVIDER_LIVE_TRANSACTION_STAGES.map(stage=>({stage,executionId:plan.executionId,status:"PASS",...(stage==="MUTATE_MINIMAL_DELTA"?{resourceCountDelta:1,newPaidResourceCreated:false}:{}),...(stage==="CLEANUP"?{ephemeralCredentialResidue:false}:{}),...(stage==="DELETE_OR_TERMINATE_READBACK"?{resourceAbsent:true}:{}),...(stage==="RESIDUE_SCAN"?{ACTIVE_PAID_COMPUTE:0,ORPHANED_BILLABLE_RESOURCE:0,BILLABLE_RESIDUE:0}:{})}));

test("P20/P22 live transaction enforces API-first ordered mutation and residue-zero",()=>{const p=compileProviderLiveTransactionV1({...base,provider:"DIGITALOCEAN",transport:"DIRECT_WORKER",executionId:"do-direct"});const e=evaluateProviderLiveTransactionV1({plan:p,receipts:stageReceipts(p)});assert.equal(e.status,"PASS");assert.equal(e.liveMatrixEdge,"DIGITALOCEAN::DIRECT_WORKER");assert.equal(e.cleanupResidueZero,true);assert.equal(p.officialApiFirst,true);assert.equal(p.manualSshNormalPath,false)});
test("live transaction fails if mutation occurs without discover/read/diff PASS",()=>{const p=compileProviderLiveTransactionV1({...base,provider:"VMWARE",transport:"DIRECT_WORKER",executionId:"vm-direct"});const r=stageReceipts(p);r.find(x=>x.stage==="READ_CURRENT").status="FAIL";const e=evaluateProviderLiveTransactionV1({plan:p,receipts:r});assert.equal(e.status,"FAIL");assert.ok(e.errors.includes("MUTATION_BEFORE_PREREQ:READ_CURRENT"))});
test("OUTCOME_UNKNOWN must reconcile before acceptance",()=>{const p=compileProviderLiveTransactionV1({...base,provider:"DIGITALOCEAN",transport:"GITHUB_SELF_HOSTED_JIT",executionId:"do-jit"});const r=stageReceipts(p);const m=r.find(x=>x.stage==="MUTATE_MINIMAL_DELTA");m.status="OUTCOME_UNKNOWN";let e=evaluateProviderLiveTransactionV1({plan:p,receipts:r});assert.equal(e.status,"FAIL");m.reconciliation={status:"RECONCILED"};e=evaluateProviderLiveTransactionV1({plan:p,receipts:r});assert.equal(e.status,"PASS")});
test("DigitalOcean create timeout reconciles exact ownership and cleans to absence",async()=>{const a=createDigitalOceanFakeAdapterV1({fault:"CREATE_TIMEOUT_AFTER_SUCCESS"});const spec=compileDigitalOceanProvisionSpecV1({executionId:"x",leaseId:"l",region:"sgp1",sizeSlug:"s-1vcpu-1gb",imageId:"img",bootstrapBundleSha256:"d".repeat(64),ttlSeconds:600,costCapMilliUsd:100});await assert.rejects(()=>a.create(spec),/OUTCOME_UNKNOWN/);let inv=await a.inventory();let rec=reconcileUnknownProviderOutcomeV1({provider:"DIGITALOCEAN",executionId:"x",leaseId:"l",inventory:inv});assert.equal(rec.state,"PRESENT_EXACT");assert.equal(rec.safeToTreatCreateAsSucceeded,true);await a.destroy(rec.matchedResourceIds[0]);inv=await a.inventory();rec=reconcileUnknownProviderOutcomeV1({provider:"DIGITALOCEAN",executionId:"x",leaseId:"l",inventory:inv});assert.equal(rec.state,"ABSENT");assert.equal(rec.safeToRetryCreate,true)});
test("VMware create timeout reconciles existing-infra resource by execution/lease ownership",async()=>{const a=createVmwareFakeAdapterV1({fault:"CREATE_TIMEOUT_AFTER_SUCCESS"});const spec=compileVmwareProvisionSpecV1({goldenImageId:"gold",goldenImageDigest:"e".repeat(64),executionId:"x",leaseId:"l",bootstrapBundleSha256:"f".repeat(64)});await assert.rejects(()=>a.create(spec),/OUTCOME_UNKNOWN/);let inv=await a.inventory();let rec=reconcileUnknownProviderOutcomeV1({provider:"VMWARE",executionId:"x",leaseId:"l",inventory:inv});assert.equal(rec.state,"PRESENT_EXACT");assert.equal(rec.userApprovalRequired,false);await a.destroy(rec.matchedResourceIds[0]);inv=await a.inventory();rec=reconcileUnknownProviderOutcomeV1({provider:"VMWARE",executionId:"x",leaseId:"l",inventory:inv});assert.equal(rec.state,"ABSENT")});
test("ambiguous ownership is blocked instead of guessed",()=>{const inv=[{resourceId:"1",tags:["atelier-execution:x","atelier-lease:l"]},{resourceId:"2",tags:["atelier-execution:x","atelier-lease:l"]}];const r=reconcileUnknownProviderOutcomeV1({provider:"DIGITALOCEAN",executionId:"x",leaseId:"l",inventory:inv});assert.equal(r.status,"BLOCKED_AMBIGUOUS");assert.equal(r.userApprovalRequired,true);assert.equal(r.safeToRetryCreate,false)});
